version: '3.9'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - .env
    command: alembic upgrade head

  backend:
    build:
      context: ./backend
    depends_on:
      - migrate
      - db
      - kafka
      - zookeeper
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: python src/moderation/main.py
    volumes:
      - ./backend:/app

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    env_file:
      - .env
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "9092:9092"
    env_file:
      - .env

  consumer:
    build:
      context: ./backend
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: python src/moderation/kafka/consumer.py

volumes:
  postgres_data:
