version: '3.9'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - .env
    command: alembic upgrade head

  backend:
    build:
      context: ./backend
    depends_on:
      - migrate
      - db
      - kafka
      - zookeeper
      - redis
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: python src/moderation/main.py
    volumes:
      - ./backend:/app

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    env_file:
      - .env
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "9092:9092"
    env_file:
      - .env

  consumer:
    build:
      context: ./backend
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: python src/moderation/kafka/consumer.py

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "4040:4040"  # Expose Nginx on port 80
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount Nginx config
      - ./backend/uploads:/uploads  # Bind uploads directory for serving media
    restart: always

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"  # Optional, for local dev
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
