version: '3.9'

services:
  db:
    container_name: postgresdb
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    container_name: db-migrate
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - .env
    command: sh -c "sleep 5 && alembic upgrade head"
    depends_on:
      - db

  backend:
    container_name: moderation-backend
    build:
      context: ./backend
    depends_on:
      - migrate
      - db
      - kafka
      - zookeeper
      - redis
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: python src/moderation/main.py
    volumes:
      - ./backend:/app

  zookeeper:
    container_name: kafka-zookeeper
    image: confluentinc/cp-zookeeper:7.4.0
    env_file:
      - .env
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka-broker
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "9092:9092"
    env_file:
      - .env

  consumer:
    container_name: kafka-consumer
    build:
      context: ./backend
    restart: always
    depends_on:
      kafka:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: python src/moderation/kafka/consumer.py

  nginx:
    container_name: nginx-server
    image: nginx:latest
    ports:
      - "4040:4040"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./backend/uploads:/uploads
    restart: always

  redis:
    container_name: redis-cache
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
