"""fix typo in content analysis

Revision ID: 36ee8e0fc571
Revises: 5ae24bc0ad67
Create Date: 2025-05-19 01:54:13.980092

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36ee8e0fc571"
down_revision: Union[str, None] = "5ae24bc0ad67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content_analysis", sa.Column("automated_flag_reason", sa.String(), nullable=True))
    op.drop_column("content_analysis", "autmotated_flag_reason")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "content_analysis", sa.Column("autmotated_flag_reason", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("content_analysis", "automated_flag_reason")
    # ### end Alembic commands ###
