"""add documents paths to content

Revision ID: 4d46e2b92f09
Revises: dfab2bd6f44c
Create Date: 2025-05-21 21:34:43.059252

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d46e2b92f09"
down_revision: Union[str, None] = "dfab2bd6f44c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content", sa.Column("document_paths", sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content", "document_paths")
    # ### end Alembic commands ###
