"""add image paths

Revision ID: 5ae24bc0ad67
Revises: af0763262b35
Create Date: 2025-05-18 15:43:33.559963

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ae24bc0ad67"
down_revision: Union[str, None] = "af0763262b35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content", sa.Column("image_paths", sa.ARRAY(sa.String()), nullable=True))
    op.add_column("users", sa.Column("username", sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "username")
    op.drop_column("content", "image_paths")
    # ### end Alembic commands ###
