"""

Revision ID: 825e19d5ae0d
Revises: 23adfded44af
Create Date: 2025-05-29 21:04:47.671144

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "825e19d5ae0d"
down_revision: Union[str, None] = "23adfded44af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content", sa.Column("video_paths", sa.ARRAY(sa.String()), nullable=True))
    op.add_column("content", sa.Column("audio_paths", sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content", "audio_paths")
    op.drop_column("content", "video_paths")
    # ### end Alembic commands ###
