"""add filename

Revision ID: dfab2bd6f44c
Revises: be59dfc534f4
Create Date: 2025-05-21 01:21:59.642309

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dfab2bd6f44c"
down_revision: Union[str, None] = "be59dfc534f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("content_analysis", sa.Column("filename", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("content_analysis", "filename")
    # ### end Alembic commands ###
