"""add client access

Revision ID: f53c799ff13b
Revises: af0763262b35
Create Date: 2025-04-21 22:49:31.124552

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f53c799ff13b"
down_revision: Union[str, None] = "af0763262b35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
