name: Playwright Tests

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Set up .env
        run: |
          cd ui
          cp .env.example .env.local  

      - name: Install dependencies
        run: |
          cd e2e
          npm ci

      - name: Set up .env
        run: cp .env.example .env

      - name: Start docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: docker-compose-ci.yaml
          up-flags: --build -d

      - name: Create fixtures
        run: docker compose exec -T backend python /app/src/moderation/scripts/load_fixtures.py

      - name: Download AI Models
        run: docker compose exec -T backend python /app/src/moderation/scripts/download_ai_models.py

      - name: Restart containers
        run: |
          docker compose -f docker-compose-ci.yaml down
          docker compose -f docker-compose-ci.yaml up -d

      - name: Install Playwright Browsers
        run: |
          cd e2e
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: |
          cd e2e
          npx playwright test

      - name: Tear down docker-compose
        if: always()
        run: docker compose -f docker-compose-ci.yaml down

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30
